[package]
name = "pseudolang-parser"
version = "0.1.0"
authors = ["Losteey <pandagaminggr@gmail.com>"]
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"]}

pseudolang_ast = { path = "../pseudolang-ast" }

[build-dependencies]
lalrpop = "0.20.2"