[package]
name = "pseudolangc_lexer"
version = "0.1.0"
authors = ["Losteey <pandagaminggr@gmail.com>"]

[dependencies]
logos = "0.14"

pseudolangc_errors = { path = "../pseudolangc_errors" }

[dev-dependencies]
pretty_assertions = "1"