[package]
name = "pseudolang-cli"
version = "0.1.0"
authors = ["Losteey <pandagaminggr@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"