[package]
name = "pseudolangc_main"
version = "0.1.0"
authors = ["Losteey <pandagaminggr@gmail.com>"]

[dependencies]
log = "0.4"

pseudolangc_lexer = { path = "../pseudolangc_lexer" }
pseudolangc_parser = { path = "../pseudolangc_parser" }
pseudolangc_codegen = { path = "../pseudolangc_codegen" }