[package]
name = "pseudolang_lexer"
version = "0.1.0"
authors = ["Losteey <pandagaminggr@gmail.com>"]

[dependencies]
logos = "0.13"

pseudolang_errors = { path = "../pseudolang_errors" }

[dev-dependencies]
pretty_assertions = "1"