[package]
name = "pseudolangc"
version = "0.1.0"
authors = ["Losteey <pandagaminggr@gmail.com>"]

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.10"
log = "0.4"

pseudolangc_main = { path = "../pseudolangc_main" }